language: python
python:
  - "2.7"
  
 install: "pip install slackclient"
 
 script:
  - perl -p -i -e "s/\r//g" tests/data/expected_events_UNIX.xml
  - python -m unittest discover -s "tests/" -p "*_test.py"
